// pst... a good regex statement to help convert wod retail shit to categories is "/(,\s*)(\/[^,\s]+),\s*(\d+)/gm"
// then do a list substitution with "\2 = \3,\n"

/obj/structure/retail/xxx_store
	desc = "Purchase all the finest outfits.. Or don't wagie.."
	product_categories = list(
		list(
			"name" = "Head",
			"icon" = "hat-cowboy",
			"products" = list(
				/obj/item/clothing/head/vampire/bandana = 10,
				/obj/item/clothing/head/vampire/bandana/red = 10,
				/obj/item/clothing/head/vampire/bandana/black = 10,
				/obj/item/clothing/head/vampire/baseballcap = 10,
				/obj/item/clothing/head/vampire/ushanka = 10,
				/obj/item/clothing/head/vampire/beanie = 10,
				/obj/item/clothing/head/vampire/beanie/black = 10,
				/obj/item/clothing/head/vampire/beanie/homeless = 10,
				/obj/item/clothing/head/vampire/hat/bucket = 10,
				/obj/item/clothing/head/vampire/hat/boater = 10,
				/obj/item/clothing/head/vampire/hat/beaver = 10,
				/obj/item/clothing/head/vampire/hat/wool = 10,
				/obj/item/clothing/head/vampire/hat/wool/blue = 10,
				/obj/item/clothing/head/vampire/hat/picture = 10,
				/obj/item/clothing/head/vampire/hat/picture/red = 10,
			),
		),

		list(
			"name" = "Accessories",
			"icon" = "glasses",
			"products" = list(
				/obj/item/clothing/glasses/vampire/yellow = 20,
				/obj/item/clothing/glasses/vampire/red = 20,
				/obj/item/clothing/glasses/vampire/sun = 20,
				/obj/item/clothing/glasses/vampire/sun/oversized = 20,
				/obj/item/clothing/glasses/vampire/sun/thin = 20,
				/obj/item/clothing/glasses/vampire/perception = 20,
				/obj/item/clothing/glasses/vampire/perception/green = 20,
				/obj/item/clothing/glasses/vampire/perception/retro = 20,
				/obj/item/clothing/glasses/vampire/perception/metal = 20,
				/obj/item/clothing/glasses/vampire/aviator = 20,
				/obj/item/clothing/glasses/vampire/aviator/green = 20,
				/obj/item/clothing/glasses/vampire/aviator/blue = 20,
				/obj/item/clothing/gloves/vampire/leather = 25,
				/obj/item/clothing/gloves/vampire/cleaning = 15,
				/obj/item/clothing/gloves/vampire/latex = 5,
				/obj/item/clothing/gloves/vampire/work = 45,
				/obj/item/clothing/neck/vampire/scarf = 10,
				/obj/item/clothing/neck/vampire/scarf/red = 10,
				/obj/item/clothing/neck/vampire/scarf/blue = 10,
				/obj/item/clothing/neck/vampire/scarf/green = 10,
				/obj/item/clothing/neck/vampire/scarf/white = 10,
				/obj/item/clothing/neck/vampire/choker = 10,
				/obj/item/clothing/neck/vampire/choker/leather = 15,
				/obj/item/clothing/neck/vampire/choker/fancy = 30,
				/obj/item/clothing/neck/vampire/choker/metal = 40,
				/obj/item/clothing/neck/vampire/choker/silver = 50,
				/obj/item/card/hunter = 25,
				/obj/item/storage/backpack/duffelbag = 100,
				/obj/item/storage/backpack = 100,
				/obj/item/storage/backpack/satchel = 100,
				/obj/item/storage/backpack/satchel/leather = 150,
			),
		),

		list(
			"name" = "Under",
			"icon" = "shirt",
			"products" = list(
				/obj/item/clothing/under/vampire/business = 250,
				/obj/item/clothing/under/vampire/leatherpants = 200,
				/obj/item/clothing/under/vampire/fancy_gray = 150,
				/obj/item/clothing/under/vampire/fancy_red = 150,
				/obj/item/clothing/under/vampire/ventrue = 50,
				/obj/item/clothing/under/vampire/ventrue/female = 50,
				/obj/item/clothing/under/vampire/office = 50,
				/obj/item/clothing/under/vampire/rich = 45,
				/obj/item/clothing/under/vampire/tremere = 35,
				/obj/item/clothing/under/vampire/tremere/female = 35,
				/obj/item/clothing/under/vampire/suit = 50,
				/obj/item/clothing/under/vampire/suit/female = 50,
				/obj/item/clothing/under/vampire/sheriff = 80,
				/obj/item/clothing/under/vampire/sheriff/female = 80,
				/obj/item/clothing/under/vampire/clerk = 90,
				/obj/item/clothing/under/vampire/clerk/female = 90,
				/obj/item/clothing/under/vampire/archivist = 60,
				/obj/item/clothing/under/vampire/archivist/female = 60,
				/obj/item/clothing/under/vampire/toreador = 30,
				/obj/item/clothing/under/vampire/toreador/female = 30,
				/obj/item/clothing/under/vampire/sexy = 25,
				/obj/item/clothing/under/vampire/slickback = 25,
				/obj/item/clothing/under/vampire/sport = 25,
				/obj/item/clothing/under/vampire/malkavian = 20,
				/obj/item/clothing/under/vampire/malkavian/female = 20,
				/obj/item/clothing/under/vampire/gothic = 20,
				/obj/item/clothing/under/vampire/brujah = 20,
				/obj/item/clothing/under/vampire/brujah/female = 20,
				/obj/item/clothing/under/vampire/baali = 20,
				/obj/item/clothing/under/vampire/baali/female = 20,
				/obj/item/clothing/under/vampire/emo = 20,
				/obj/item/clothing/under/vampire/red = 20,
				/obj/item/clothing/under/vampire/bouncer = 15,
				/obj/item/clothing/under/vampire/mechanic = 20,
				/obj/item/clothing/under/vampire/black = 20,
				/obj/item/clothing/under/vampire/nosferatu = 15,
				/obj/item/clothing/under/vampire/nosferatu/female = 15,
				/obj/item/clothing/under/vampire/gangrel = 15,
				/obj/item/clothing/under/vampire/gangrel/female = 15,
				/obj/item/clothing/under/vampire/larry = 15,
				/obj/item/clothing/under/vampire/bandit = 15,
				/obj/item/clothing/under/vampire/turtleneck_white = 15,
				/obj/item/clothing/under/vampire/turtleneck_black = 15,
				/obj/item/clothing/under/vampire/turtleneck_red = 15,
				/obj/item/clothing/under/vampire/turtleneck_navy = 15,
				/obj/item/clothing/under/vampire/biker = 15,
				/obj/item/clothing/under/vampire/burlesque = 15,
				/obj/item/clothing/under/vampire/burlesque/daisyd = 10,
			),
		),

		list(
			"name" = "Outerwear",
			"icon" = "vest",
			"products" = list(
				/obj/item/clothing/suit/vampire/slickbackcoat = 500,
				/obj/item/clothing/suit/vampire/majima_jacket = 100,
				/obj/item/clothing/suit/vampire/labcoat = 75,
				/obj/item/clothing/suit/vampire/fancy_gray = 50,
				/obj/item/clothing/suit/vampire/fancy_red = 50,
				/obj/item/clothing/suit/vampire/trench = 45,
				/obj/item/clothing/suit/vampire/trench/alt = 35,
				/obj/item/clothing/suit/vampire/coat = 15,
				/obj/item/clothing/suit/vampire/coat/alt = 15,
				/obj/item/clothing/suit/vampire/jacket = 15,
				/obj/item/clothing/suit/vampire/coat/winter = 15,
				/obj/item/clothing/suit/vampire/coat/winter/alt = 15,
				/obj/item/clothing/suit/jacket/miljacket = 25,
				/obj/item/clothing/suit/vampire/militaryjacket/white = 25,
				/obj/item/clothing/suit/vampire/militaryjacket/tan = 25,
				/obj/item/clothing/suit/vampire/militaryjacket/navy = 25,
				/obj/item/clothing/suit/vampire/militaryjacket/grey = 25,
				/obj/item/clothing/suit/vampire/militaryjacket/black = 25,
				/obj/item/clothing/suit/vampire/bomber = 25,
				/obj/item/clothing/suit/vampire/bomber/retro = 25,
				/obj/item/clothing/suit/vampire/varsity = 25,
				/obj/item/clothing/suit/vampire/varsity/purple = 25,
				/obj/item/clothing/suit/vampire/letterman = 25,
				/obj/item/clothing/suit/jacket/letterman = 25,
				/obj/item/clothing/suit/jacket/letterman_red = 25,
				/obj/item/clothing/suit/vampire/flannel = 15,
				/obj/item/clothing/suit/vampire/flannel/red = 15,
				/obj/item/clothing/suit/vampire/flannel/aqua = 15,
				/obj/item/clothing/suit/vampire/flannel/brown = 15,
				/obj/item/clothing/suit/vampire/flannel/short = 15,
				/obj/item/clothing/suit/vampire/flannel/short/red = 15,
				/obj/item/clothing/suit/vampire/flannel/short/aqua = 15,
				/obj/item/clothing/suit/vampire/flannel/short/brown = 15,
				/obj/item/clothing/suit/hooded/hoodie/parka = 35,
				/obj/item/clothing/suit/hooded/hoodie/parka/yellow = 35,
				/obj/item/clothing/suit/hooded/hoodie/parka/red = 35,
				/obj/item/clothing/suit/hooded/hoodie/parka/purple = 35,
				/obj/item/clothing/suit/hooded/hoodie/parka/blue = 35,
				/obj/item/clothing/suit/hooded/hoodie/parka_vintage = 45,
			),
		),

		list(
			"name" = "Shoes",
			"icon" = "socks",
			"products" = list(
				/obj/item/clothing/shoes/vampire = 10,
				/obj/item/clothing/shoes/vampire/brown = 10,
				/obj/item/clothing/shoes/vampire/white = 10,
				/obj/item/clothing/shoes/sandal/velcro = 10,
				/obj/item/clothing/shoes/sandal/alt/velcro = 10,
				/obj/item/clothing/shoes/vampire/jackboots = 10,
				/obj/item/clothing/shoes/vampire/jackboots/work = 10,
				/obj/item/clothing/shoes/vampire/sneakers = 10,
				/obj/item/clothing/shoes/vampire/sneakers/red = 10,
				/obj/item/clothing/shoes/vampire/heels = 35,
				/obj/item/clothing/shoes/vampire/heels/red = 35,
				/obj/item/clothing/shoes/vampire/heels/white = 35,
				/obj/item/clothing/shoes/vampire/businessscaly = 35,
				/obj/item/clothing/shoes/vampire/businessblack = 35,
				/obj/item/clothing/shoes/vampire/businesstip = 50,
			),
		),

		list(
			"name" = "Paraphernalia",
			"icon" = "smoking",
			"products" = list(
			),
		),

		list(
			"name" = "Lewd",
			"icon" = "heart",
			"products" = list(
			),
		),
	)
